local PokemonEV = {}

PokemonEV["Bulbasaur"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ivysaur"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Venusaur"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Charmander"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Charmeleon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Charizard"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Squirtle"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Wartortle"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Blastoise"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Caterpie"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Metapod"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Butterfree"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Weedle"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Kakuna"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Beedrill"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Pidgey"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Pidgeotto"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Pidgeot"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=3}
PokemonEV["Rattata"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Raticate"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Spearow"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Fearow"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Ekans"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Arbok"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pikachu"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Raichu"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=3}
PokemonEV["Sandshrew"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sandslash"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Nidoran F"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Nidorina"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Nidoqueen"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Nidoran M"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Nidorino"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Nidoking"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Clefairy"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Clefable"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Vulpix"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Ninetales"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=1}
PokemonEV["Jigglypuff"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Wigglytuff"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Zubat"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Golbat"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Oddish"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gloom"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Vileplume"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Paras"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Parasect"] = {["HP"]=0,["ATK"]=2,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Venonat"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Venomoth"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Diglett"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Dugtrio"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Meowth"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Persian"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Psyduck"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Golduck"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mankey"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Primeape"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Growlithe"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Arcanine"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Poliwag"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Poliwhirl"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Poliwrath"] = {["HP"]=0,["ATK"]=0,["DEF"]=3,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Abra"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kadabra"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Alakazam"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Machop"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Machoke"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Machamp"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bellsprout"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Weepinbell"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Victreebel"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tentacool"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Tentacruel"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Geodude"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Graveler"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Golem"] = {["HP"]=0,["ATK"]=0,["DEF"]=3,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ponyta"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Rapidash"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Slowpoke"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Slowbro"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Magnemite"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Magneton"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Farfetch'd"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Doduo"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dodrio"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Seel"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Dewgong"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Grimer"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Muk"] = {["HP"]=1,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Shellder"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cloyster"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gastly"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Haunter"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gengar"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Onix"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Drowzee"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Hypno"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Krabby"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kingler"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Voltorb"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Electrode"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Exeggcute"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Exeggutor"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cubone"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Marowak"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Hitmonlee"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Hitmonchan"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Lickitung"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Koffing"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Weezing"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Rhyhorn"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Rhydon"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Chansey"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tangela"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kangaskhan"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Horsea"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Seadra"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Goldeen"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Seaking"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Staryu"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Starmie"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Mr. Mime"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Scyther"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Jynx"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Electabuzz"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Magmar"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pinsir"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tauros"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Magikarp"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Gyarados"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lapras"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ditto"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Eevee"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Vaporeon"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Jolteon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Flareon"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Porygon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Omanyte"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Omastar"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kabuto"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kabutops"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Aerodactyl"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Snorlax"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Articuno"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Zapdos"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Moltres"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dratini"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dragonair"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dragonite"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mewtwo"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mew"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Chikorita"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Bayleef"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Meganium"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Cyndaquil"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Quilava"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Typhlosion"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Totodile"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Croconaw"] = {["HP"]=0,["ATK"]=1,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Feraligatr"] = {["HP"]=0,["ATK"]=2,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sentret"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Furret"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Hoothoot"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Noctowl"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ledyba"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Ledian"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Spinarak"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ariados"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Crobat"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=3}
PokemonEV["Chinchou"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lanturn"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pichu"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Cleffa"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Igglybuff"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Togepi"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Togetic"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Natu"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Xatu"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Mareep"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Flaaffy"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ampharos"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bellossom"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Marill"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Azumarill"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sudowoodo"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Politoed"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Hoppip"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Skiploom"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Jumpluff"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=3}
PokemonEV["Aipom"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Sunkern"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sunflora"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Yanma"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Wooper"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Quagsire"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Espeon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Umbreon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Murkrow"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Slowking"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Misdreavus"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Unown"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Wobbuffet"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Girafarig"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pineco"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Forretress"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dunsparce"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gligar"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Steelix"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Snubbull"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Granbull"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Qwilfish"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Scizor"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Shuckle"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Heracross"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sneasel"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Teddiursa"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ursaring"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Slugma"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Magcargo"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Swinub"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Piloswine"] = {["HP"]=1,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Corsola"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Remoraid"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Octillery"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Delibird"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Mantine"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Skarmory"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Houndour"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Houndoom"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kingdra"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Phanpy"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Donphan"] = {["HP"]=0,["ATK"]=1,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Porygon2"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Stantler"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Smeargle"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Tyrogue"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Hitmontop"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Smoochum"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Elekid"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Magby"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Miltank"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Blissey"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Raikou"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Entei"] = {["HP"]=1,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Suicune"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Larvitar"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pupitar"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tyranitar"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lugia"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Ho-oh"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Celebi"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Treecko"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Grovyle"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Sceptile"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=3}
PokemonEV["Torchic"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Combusken"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Blaziken"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mudkip"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Marshtomp"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Swampert"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Poochyena"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mightyena"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Zigzagoon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Linoone"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Wurmple"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Silcoon"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Beautifly"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cascoon"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dustox"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Lotad"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Lombre"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Ludicolo"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Seedot"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Nuzleaf"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Shiftry"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Taillow"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Swellow"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Wingull"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Pelipper"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ralts"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kirlia"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gardevoir"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Surskit"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Masquerain"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Shroomish"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Breloom"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Slakoth"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Vigoroth"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Slaking"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Nincada"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ninjask"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Shedinja"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Whismur"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Loudred"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Exploud"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Makuhita"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Hariyama"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Azurill"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Nosepass"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Skitty"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Delcatty"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Sableye"] = {["HP"]=0,["ATK"]=1,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mawile"] = {["HP"]=0,["ATK"]=1,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Aron"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lairon"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Aggron"] = {["HP"]=0,["ATK"]=0,["DEF"]=3,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Meditite"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Medicham"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Electrike"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Manectric"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Plusle"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Minun"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Volbeat"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Illumise"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Roselia"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gulpin"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Swalot"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Carvanha"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sharpedo"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Wailmer"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Wailord"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Numel"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Camerupt"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Torkoal"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Spoink"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Grumpig"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Spinda"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Trapinch"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Vibrava"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Flygon"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Cacnea"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cacturne"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Swablu"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Altaria"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Zangoose"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Seviper"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lunatone"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Solrock"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Barboach"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Whiscash"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Corphish"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Crawdaunt"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Baltoy"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Claydol"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Lileep"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Cradily"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Anorith"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Armaldo"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Feebas"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Milotic"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Castform"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kecleon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Shuppet"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Banette"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Duskull"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Dusclops"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Tropius"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Chimecho"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Absol"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Wynaut"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Snorunt"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Glalie"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Spheal"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sealeo"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Walrein"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Clamperl"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Huntail"] = {["HP"]=0,["ATK"]=1,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gorebyss"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Relicanth"] = {["HP"]=1,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Luvdisc"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Bagon"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Shelgon"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Salamence"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Beldum"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Metang"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Metagross"] = {["HP"]=0,["ATK"]=0,["DEF"]=3,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Regirock"] = {["HP"]=0,["ATK"]=0,["DEF"]=3,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Regice"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Registeel"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Latias"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Latios"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kyogre"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Groudon"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Rayquaza"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Jirachi"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Deoxys"] = {["HP"]=999,["ATK"]=999,["DEF"]=999,["SPATK"]=999,["SPDEF"]=999,["SPD"]=999}
PokemonEV["Turtwig"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Grotle"] = {["HP"]=0,["ATK"]=1,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Torterra"] = {["HP"]=0,["ATK"]=2,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Chimchar"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Monferno"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Infernape"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Piplup"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Prinplup"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Empoleon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Starly"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Staravia"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Staraptor"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bidoof"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bibarel"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kricketot"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Kricketune"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Shinx"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Luxio"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Luxray"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Budew"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Roserade"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cranidos"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Rampardos"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Shieldon"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bastiodon"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Burmy"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Wormadam"] = {["HP"]=999,["ATK"]=999,["DEF"]=999,["SPATK"]=999,["SPDEF"]=999,["SPD"]=999}
PokemonEV["Mothim"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Combee"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Vespiquen"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Pachirisu"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Buizel"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Floatzel"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Cherubi"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cherrim"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Shellos"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gastrodon"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ambipom"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Drifloon"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Drifblim"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Buneary"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Lopunny"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Mismagius"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Honchkrow"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Glameow"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Purugly"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Chingling"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Stunky"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Skuntank"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bronzor"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bronzong"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Bonsly"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mime Jr."] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Happiny"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Chatot"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Spiritomb"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Gible"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gabite"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Garchomp"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Munchlax"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Riolu"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lucario"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Hippopotas"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Hippowdon"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Skorupi"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Drapion"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Croagunk"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Toxicroak"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Carnivine"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Finneon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Lumineon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Mantyke"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Snover"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Abomasnow"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Weavile"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Magnezone"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lickilicky"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Rhyperior"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tangrowth"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Electivire"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Magmortar"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Togekiss"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Yanmega"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Leafeon"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Glaceon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gliscor"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mamoswine"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Porygon-Z"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gallade"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Probopass"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Dusknoir"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Froslass"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Rotom"] = {["HP"]=999,["ATK"]=999,["DEF"]=999,["SPATK"]=999,["SPDEF"]=999,["SPD"]=999}
PokemonEV["Uxie"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Mesprit"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Azelf"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dialga"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Palkia"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Heatran"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Regigigas"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Giratina"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cresselia"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Phione"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Manaphy"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Darkrai"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Shaymin"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Arceus"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Victini"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Snivy"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Servine"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Serperior"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=3}
PokemonEV["Tepig"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pignite"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Emboar"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Oshawott"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dewott"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Samurott"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Patrat"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Watchog"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lillipup"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Herdier"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Stoutland"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Purrloin"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Liepard"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Pansage"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Simisage"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Pansear"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Simisear"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Panpour"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Simipour"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Munna"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Musharna"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pidove"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tranquill"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Unfezant"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Blitzle"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Zebstrika"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Roggenrola"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Boldore"] = {["HP"]=0,["ATK"]=1,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gigalith"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Woobat"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Swoobat"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Drilbur"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Excadrill"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Audino"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Timburr"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gurdurr"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Conkeldurr"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tympole"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Palpitoad"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Seismitoad"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Throh"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sawk"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sewaddle"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Swadloon"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Leavanny"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Venipede"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Whirlipede"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Scolipede"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=3}
PokemonEV["Cottonee"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Whimsicott"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Petilil"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lilligant"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Basculin"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Sandile"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Krokorok"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Krookodile"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Darumaka"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Darmanitan"] = {["HP"]=999,["ATK"]=999,["DEF"]=999,["SPATK"]=999,["SPDEF"]=999,["SPD"]=999}
PokemonEV["Maractus"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dwebble"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Crustle"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Scraggy"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Scrafty"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Sigilyph"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Yamask"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cofagrigus"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tirtouga"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Carracosta"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Archen"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Archeops"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Trubbish"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Garbodor"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Zorua"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Zoroark"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Minccino"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Cinccino"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Gothita"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Gothorita"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Gothitelle"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Solosis"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Duosion"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Reuniclus"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ducklett"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Swanna"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Vanillite"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Vanillish"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Vanilluxe"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Deerling"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Sawsbuck"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Emolga"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Karrablast"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Escavalier"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Foongus"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Amoonguss"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Frillish"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Jellicent"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Alomomola"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Joltik"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Galvantula"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Ferroseed"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Ferrothorn"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Klink"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Klang"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Klinklang"] = {["HP"]=0,["ATK"]=0,["DEF"]=3,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tynamo"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Eelektrik"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Eelektross"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Elgyem"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Beheeyem"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Litwick"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Lampent"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Chandelure"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Axew"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Fraxure"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Haxorus"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cubchoo"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Beartic"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cryogonal"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Shelmet"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Accelgor"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Stunfisk"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mienfoo"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mienshao"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Druddigon"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Golett"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Golurk"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pawniard"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bisharp"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bouffalant"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Rufflet"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Braviary"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Vullaby"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Mandibuzz"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Heatmor"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Durant"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Deino"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Zweilous"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Hydreigon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Larvesta"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Volcarona"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Cobalion"] = {["HP"]=0,["ATK"]=0,["DEF"]=3,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Terrakion"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Virizion"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Tornadus"] = {["HP"]=999,["ATK"]=999,["DEF"]=999,["SPATK"]=999,["SPDEF"]=999,["SPD"]=999}
PokemonEV["Thundurus"] = {["HP"]=999,["ATK"]=999,["DEF"]=999,["SPATK"]=999,["SPDEF"]=999,["SPD"]=999}
PokemonEV["Reshiram"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Zekrom"] = {["HP"]=0,["ATK"]=3,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Landorus"] = {["HP"]=999,["ATK"]=999,["DEF"]=999,["SPATK"]=999,["SPDEF"]=999,["SPD"]=999}
PokemonEV["Kyurem"] = {["HP"]=999,["ATK"]=999,["DEF"]=999,["SPATK"]=999,["SPDEF"]=999,["SPD"]=999}
PokemonEV["Keldeo"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Meloetta"] = {["HP"]=999,["ATK"]=999,["DEF"]=999,["SPATK"]=999,["SPDEF"]=999,["SPD"]=999}
PokemonEV["Genesect"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Chespin"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Quilladin"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Chesnaught"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Fennekin"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Braixen"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Delphox"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Froakie"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Frogadier"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Greninja"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=3}
PokemonEV["Bunnelby"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Diggersby"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Fletchling"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Fletchinder"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Talonflame"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=3}
PokemonEV["Scatterbug"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Spewpa"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Vivillon"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Litleo"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pyroar"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Flabébé"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Floette"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Florges"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Skiddo"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gogoat"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pancham"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pangoro"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Furfrou"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Espurr"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Meowstic"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Honedge"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Doublade"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Aegislash"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Spritzee"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Aromatisse"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Swirlix"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Slurpuff"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Inkay"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Malamar"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Binacle"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Barbaracle"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Skrelp"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Dragalge"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Clauncher"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Clawitzer"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=2,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Helioptile"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Heliolisk"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=1,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Tyrunt"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Tyrantrum"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Amaura"] = {["HP"]=1,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Aurorus"] = {["HP"]=2,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Sylveon"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Hawlucha"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Dedenne"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Carbink"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Goomy"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=1,["SPD"]=0}
PokemonEV["Sliggoo"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Goodra"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=3,["SPD"]=0}
PokemonEV["Klefki"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Phantump"] = {["HP"]=0,["ATK"]=1,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Trevenant"] = {["HP"]=0,["ATK"]=2,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Pumpkaboo"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Gourgeist"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Bergmite"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Avalugg"] = {["HP"]=0,["ATK"]=0,["DEF"]=2,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Noibat"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=1}
PokemonEV["Noivern"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=2}
PokemonEV["Xerneas"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Yveltal"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Zygarde"] = {["HP"]=3,["ATK"]=0,["DEF"]=0,["SPATK"]=0,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Diancie"] = {["HP"]=0,["ATK"]=0,["DEF"]=1,["SPATK"]=0,["SPDEF"]=2,["SPD"]=0}
PokemonEV["Hoopa"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}
PokemonEV["Volcanion"] = {["HP"]=0,["ATK"]=0,["DEF"]=0,["SPATK"]=3,["SPDEF"]=0,["SPD"]=0}

return PokemonEV
